# Generated by Django 5.2.8 on 2025-11-30 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=250, verbose_name="Место выполнения привычки")),
                (
                    "time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время, когда необходимо выполнять привычку"
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=500, verbose_name="Действие, которое представляет собой привычка"),
                ),
                ("is_enjoyable", models.BooleanField(blank=True, null=True, verbose_name="Привычка приятная?")),
                (
                    "period_in_days",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Периодичность привычки в днях"),
                ),
                (
                    "reward",
                    models.CharField(max_length=500, verbose_name="Действие, которое является вознаграждением"),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(verbose_name="Продолжительность выполнения привычки в секундах"),
                ),
                ("is_public", models.BooleanField(blank=True, null=True, verbose_name="Привычка публичная?")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите приятную привычку, которая будет вознаграждением",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="users.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
