# Generated by Django 5.2.8 on 2025-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_habit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "привычка", "verbose_name_plural": "привычки"},
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время, когда необходимо выполнять привычку"),
        ),
    ]
