# Generated by Django 5.2.8 on 2025-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_habit_options_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Действие, которое является вознаграждением"
            ),
        ),
    ]
